server:
  port: 9091
  id: local

spring:
  application:
    name: sonarqube
info.app:
  name: Sonarqube POC
  version: 0.0.1

logging:
  config: src/main/resources/logback.xml
  path: logs/sonarqube
  file: sonarqube
